### ISSUE TITLE
The *Add New* button in *Organization* sheet is not working

### ISSUE THREAD

**Issue by TW-ASMP** [TW-ASMP/AIW#12]
## Issue Description

https://user-images.githubusercontent.com/64802605/192375356-5738870c-fff5-4c4e-93fa-1bb8c31be493.mp4

**Comment by feiterry** [comment]
Base on your description video, this  defect should be in 'Organization' Sheet/tab instead of 'Roles', I am looking into it now.

**Comment by feiterry** [comment]
I have reviewed the code and found below to verify with you:
1. 'Add New' button in Organization tab works, it only add new at last and create incremental ID. 
2. The sample 'Add Sibling' button in 'Production-Line' tab is different function, it  insert sibling row  next to the current selected row.
3. It seems these two function are based on requirements originally, so please confirm that you want to change the 'Add New' to 'Add Sibling'

**Comment by TW-ASMP** [comment]
The real issue seem to be that if the selection is on the data range of the table, then now rows cannot be added.

**Comment by ZainHKazmi** [comment]
@TnyHng -- clicking on Add new still does nothing
