### ISSUE TITLE
*Move Selected Row* bottom in *Role* sheet disables my ability to scroll through the data

### ISSUE THREAD

**Issue by TW-ASMP** [TW-ASMP/AIW#13]
## Issue Description
https://user-images.githubusercontent.com/64802605/192378050-d7a8ef89-1f9b-49ce-ac55-58ee0d97d170.mp4

## Missed in the Video
The "Move Selected Row* button is also found in the following sheets
- Product-Lines
- Spaces
The fix needs to be implemented in these sheets too.

**Comment by feiterry** [comment]
fixed, there is a bug founded in code before calling LoadRowMover function, the Application.ScreenUpdate should not be disabled.
search #13 for details
