### ISSUE TITLE
EDP_AddNew&ChangeExisting sheet data column modification.

### ISSUE THREAD

**Issue by TW-ASMP** [TW-ASMP/AIW#18]

**Comment by TW-ASMP** [comment]
The EDP_AddNew&ChangeExisting must have these columns

Very Important: DO NOT CHANGE THE CALCULATION OF EXISTING COLUMNS

[DP Entity Template 2022.xlsx](https://github.com/TW-ASMP/AIW/files/9826035/DP.Entity.Template.2022.xlsx)

**Comment by feiterry** [comment]
Fixed this with #16 together, created new power query and kept previous by add '-old'
