### ISSUE TITLE
DP PM Task 1 sheet column changes

### ISSUE THREAD

**Issue by TW-ASMP** [TW-ASMP/AIW#19]
Please change the existing set of columns to the new set of columns described below

![Image](https://user-images.githubusercontent.com/64802605/196856298-59d43d35-748b-45a7-97f2-a695b0841459.png)

**IMPORTANT**: please do not change the calculation of existing columns

**Comment by feiterry** [comment]
Additional requirements from Tony's Notes:
Planner rule for generated work task    value set to '1'
Supervisor rule for generated work task value set to '1'
