### ISSUE TITLE
In *Spaces* sheet, the button "Populate / Refresh Parent Entity Number" does not work

### ISSUE THREAD

**Issue by TW-ASMP** [TW-ASMP/AIW#5]
## Description
See image below for the button
![image](https://user-images.githubusercontent.com/64802605/192335783-37b88c83-d5d3-4deb-bb15-559c7f8cb1bc.png)

## Desired Outcome

The image below show the expected parent entity numbers (in the last column),  determined using information from *Space Entity Number* column and *Level* column

![Image](https://user-images.githubusercontent.com/64802605/192592116-f2f58299-974c-4ccf-b32c-f47df6d71d06.png)

**Comment by TW-ASMP** [comment]
@feiterry, please note that I have refined the issue description

**Comment by ZainHKazmi** [comment]
Still Doesn't work @TnyHng

**Comment by ZainHKazmi** [comment]
Completed
