### ISSUE TITLE
MINOR REWORK: Add Row buttons in Section 2 & 3 of *Role* sheet cause the primary key value to be overwritten

### ISSUE THREAD

**Issue by TW-ASMP** [TW-ASMP/AIW#8]
## Desired State

Please see video below for 
https://user-images.githubusercontent.com/64802605/192357747-a4fdd9de-c26b-4242-afb9-d36915aff537.mp4

Please note,
* behaviour need to be fixed for Section 2 and 3

**Comment by TW-ASMP** [comment]
https://user-images.githubusercontent.com/64802605/195756394-fbe64936-b3ee-4201-8a23-588eeaac3c6d.mp4

**Comment by feiterry** [comment]
fixed rework, now both add Row buttons at section 2 and 3 works as expected
