### ISSUE TITLE
NOTE ADDED: Wrong parent data used in *EDP_Renumbered* sheet

### ISSUE THREAD

**Issue by TW-ASMP** [TW-ASMP/AIW#9]
## Issue
**See Video for issue description**
https://user-images.githubusercontent.com/64802605/192361026-2f73bf3c-86c3-41f9-b621-564b3240c59b.mp4
This change should be applied to *EDP_Renumbered* worksheet

**Comment by TW-ASMP** [comment]
@feiterry. I noticed that the column sequence in EDP_renumbered sheet has changed. I forgot to tell you that our data upload system expects the column sequence and spelling to remain exactly the same. For your reference, this is what it used to look like.

![Image](https://user-images.githubusercontent.com/64802605/193958112-7b7ff46a-142c-483d-8d93-04d1aec51ba3.png)

**Comment by feiterry** [comment]
@TW-ASMP , OK got it, let me fix it.

**Comment by feiterry** [comment]
@TW-ASMP , fixed, this is caused by a Power Query known defect, that reorder column function wouldn't change data view sequence, fixed it by a work around from web
